print("helloword")
print("2+3",end='=')
print(2+3)
print("hi","hi",sep="...",end="... ")
print("hi")
print("escape\nsequence")
print("escape\t\tsequence")
print("it's hero time!")
print('it\'s hero time!')